name: "deploy"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags-ignore: [ "**" ]

concurrency:
  group: ${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    environment:
      name: "production"
      url: "https://webui.advntr.dev"
    steps:
      - name: "setup env"
        id: "setup"
        uses: "KyoriPowered/ci-cookbook/actions/setup-java-env@f3b9a3fbb31e9f4320d855e7be17b028522e87be" # 2026.02.07
        with:
          runtime_version: 21
          publishing_branch_regex: "main"
          gradle_warning_mode: "all"
      - name: "setup / login to ghcr"
        uses: "docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121" # v4.1.0
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: "publish / docker image"
        run: ./gradlew jib -Djib.console=plain --stacktrace
